import json
from agents import Runner,Agent,set_tracing_export_api_key
from src.controllers.docs_generator import generate_assignment_docx
from src.models.pydantic_model import data
from src.agents.content_agent import content_agent
from src.configs.env_config import OPENAI_API_KEY
from src.controllers.generate_image import generate_image, generate_image_via_advanced_web

async def chat_controller(chat_data:data,agent_config,):
    set_tracing_export_api_key(OPENAI_API_KEY)

    json_data = chat_data.model_dump_json()
    orchistrator_agent = Agent(
        name="orchistrator agent",
        instructions="""
        You are an Assignment Orchestrator.

        You never write assignment answers.

        Your responsibilities are:

        1. Understand the user's request.
        2. Collect all missing information.
        3. Validate the information.
        4. Create a structured request.
        5. Handoff the request to the Content Agent.

        Collect:

        - Assignment Number
        - Course Code
        - Semester
        - Student Name
        - Registration ID
        - Questions
        - Language

        Never generate academic content.

        If anything is missing, ask the user.

        When everything is complete don't ask confirmation questions just handoff to the Content Agent.
        """,
        handoffs=[content_agent]
    )
    # result = await Runner.run(
    #     input=json_data,
    #     starting_agent=orchistrator_agent,
    #     run_config=agent_config.config(),

    # )
    # agent_raw_output = result.final_output
    agent_raw_output = {
        "assignment_no": 1,
        "course_code": 8611,
        "semester": "Spring 2026",
        "student_name": "FARHAT NAZ",
        "registration_id": 844005,
        "questions": [
            {
                "question_number": 1,
                "question_text": "Why in human civilizations do critical thinkers challenge the status quo?",
                "introduction": "Throughout the historical trajectory of human civilizations, the tension between established social structures and transformative ideas has served as the primary engine of intellectual, social, and political evolution. The status quo represents the consolidated norms, institutionalized power dynamics, dominant ideological paradigms, and socio-economic hierarchies that govern a given society at a particular historical moment. While these established structures provide structural stability, social cohesion, and predictability, they inherently tend toward institutional rigidity, socio-economic stratification, and the preservation of privileged interests. Critical thinkers operate as catalyst agents within this socio-historical dynamic, utilizing rigorous analytical inquiry, moral reflexivity, and intellectual courage to interrogate the unquestioned assumptions and structural inequalities embedded within orthodox paradigms.\n\nThe act of challenging the status quo is rarely an exercise in arbitrary rebellion; rather, it is a deeply philosophical and epistemological endeavor aimed at exposing the contradictions between social ideals and lived realities. From the Socratic dialogues in ancient Athens to the Enlightenment philosophers, anti-colonial theorists, and contemporary civil rights advocates, critical thinkers have systematically destabilized dominant narratives that present existing power structures as natural, inevitable, or divinely ordained. By deconstructing these naturalized ideologies, critical thinkers reveal the socio-historical contingency of institutional arrangements, thereby opening up imaginative possibilities for more equitable, rational, and humane alternative futures.\n\nFurthermore, the impulse to challenge established orthodoxies stems from a profound recognition of human vulnerability to systemic exploitation, dogmatism, and cognitive stagnation. When institutions prioritize self-preservation over justice, or dogmatic compliance over empirical truth, critical thinkers intervene to prevent civilizational decline. Their critiques act as necessary corrective mechanisms that prevent societies from descending into totalitarian control, intellectual paralysis, or systemic moral corruption. Understanding why and how critical thinkers challenge the status quo requires a multi-dimensional examination of political theory, sociology, historical materialism, and cognitive philosophy.",
                "sections": [
                    {
                        "heading": "Historical Dynamics of Hegemony and Resistance",
                        "explanation": "The historical progression of human societies can be fundamentally understood through the dialectical interaction between dominant power structures and resistive intellectual movements. Hegemony, as conceptualized by Antonio Gramsci, refers to the way ruling elites maintain control not merely through coercion, but through the production and dissemination of cultural norms, values, and beliefs that legitimize their dominance. The status quo is thus reinforced through cultural hegemony, making systemic inequalities appear rational, universal, and beneficial to all social strata. Critical thinkers function as organic intellectuals who pierce through this manufactured consent, exposing the underlying mechanics of exploitation and power consolidation that sustain established regimes across different historical epochs.\n\nHistorically, every epochal shift—from feudalism to industrial capitalism, or from absolute monarchies to constitutional democracies—was preceded by rigorous intellectual critique that destabilized prevailing hegemonies. During the European Enlightenment, thinkers like Voltaire, Rousseau, and Montesquieu challenged the divine right of kings and the dogmatic authority of the Church, laying the philosophical groundwork for democratic governance and individual rights. Similarly, in anti-colonial struggles across Asia, Africa, and Latin America, critical intellectuals such as Frantz Fanon, Mahatma Gandhi, and Aimé Césaire dismantled the moral and intellectual justifications of imperial domination. These historical precedents demonstrate that challenging the status quo is essential for liberating subjugated populations from structural violence and ideological domination.\n\nIn contemporary contexts, the dynamics of hegemony have expanded into the spheres of globalized neoliberal capital, digital media, and technocratic governance. Critical thinkers today continue this historical trajectory by examining how modern institutions, algorithms, and market forces perpetuate systemic inequities. By documenting how contemporary power structures manufacture consent through sophisticated media channels and consumer culture, critical scholars provide marginalized communities with the analytical tools needed to articulate their grievances and mobilize for structural emancipation. Thus, the historical dialectic between hegemony and resistance remains an active, ongoing process driven by critical intellectual intervention."
                    },
                    {
                        "heading": "Epistemological Disruption and the Pursuit of Truth",
                        "explanation": "At its core, critical thinking is an epistemological practice devoted to interrogating the foundations of knowledge, truth claims, and rational justification. Human civilizations frequently fall prey to dogmatism, where inherited traditions, religious doctrines, or institutional orthodoxies are accepted as absolute, immutable truths. Critical thinkers introduce epistemological disruption by demanding empirical evidence, logical consistency, and philosophical coherence from dominant truth narratives. By refusing to accept statements on the basis of authority alone, critical thinkers destabilize the epistemological monopoly held by elite institutions, fostering a culture of scientific inquiry, skepticism, and cognitive accountability.\n\nThis epistemological disruption is clearly illustrated in the history of scientific revolutions, as analyzed by Thomas Kuhn. Established scientific paradigms often resist revolutionary discoveries that threaten existing theoretical frameworks, leading to institutional resistance against new truths. Figures such as Copernicus, Galileo, and Darwin directly challenged the prevailing religious and scientific orthodoxies of their respective eras, enduring intense persecution, censorship, and social ostracization. Their willingness to confront established dogmas ultimately catalyzed paradigm shifts that fundamentally reordered humanity's understanding of the cosmos, biological evolution, and the natural world, demonstrating that intellectual progress requires the Courage to disrupt institutional consensus.\n\nMoreover, critical epistemology emphasizes that knowledge production is never neutral; it is inevitably entangled with power relations, institutional interests, and social positionalities. Critical theorists like Michel Foucault demonstrated that 'regimes of truth' are constructed by dominant institutions to regulate human behavior and maintain social order. Critical thinkers disrupt these knowledge-power configurations by elevating subjugated knowledges—the perspectives, experiences, and truths of historically marginalized groups. In doing so, critical thinkers transform epistemology from an instrument of social control into a vehicle for intellectual liberation and cognitive democratization."
                    },
                    {
                        "heading": "Institutional Inertia and Systemic Reform",
                        "explanation": "Complex human institutions—whether state bureaucracies, religious hierarchies, educational systems, or economic corporations—exhibit a powerful inherent tendency toward institutional inertia. Over time, institutions develop self-reinforcing mechanisms designed to preserve their organizational structures, buffer themselves against external critiques, and safeguard the privileges of elite stakeholders. This organizational rigidity often leads to functional decay, bureaucratic paralysis, and an inability to adapt to changing environmental, technological, or socio-economic conditions. Critical thinkers challenge the status quo to overcome this inertia, serving as essential agents of institutional renewal and structural adaptation.\n\nWithout persistent critique, institutional inertia inevitably converts social structures into instrumentalities of systemic oppression and inefficiency. For example, during the Industrial Revolution, institutional systems treated labor primarily as a disposable commodity, resulting in extreme exploitation, child labor, and unsafe working environments. Critical thinkers, social reformers, and labor organizers systematically analyzed these institutional failures, formulating theoretical frameworks that justified labor rights, workplace safety regulations, and public welfare systems. Their critique forced stubborn institutional frameworks to adapt, thereby preventing catastrophic social collapse and laying the foundations for the modern welfare state.\n\nIn the modern era, institutional inertia manifests strongly in responses to climate change, economic inequality, and systemic racism. Institutional bodies frequently engage in superficial reforms or symbolic gestures that preserve the core status quo while appearing to address public grievances. Critical thinkers expose these superficial adaptations by conducting rigorous structural analyses, demonstrating that meaningful reform requires fundamental restructuring rather than incremental adjustments. By highlighting the gap between institutional promises and actual structural outcomes, critical thinkers create the social and political pressure necessary to break through bureaucratic inertia and drive genuine institutional reform."
                    },
                    {
                        "heading": "Ethical Imperatives and Human Rights Evolution",
                        "explanation": "The challenge to the status quo is fundamentally anchored in ethical imperatives and the continuous evolution of human rights standards. Societies throughout history have routinely institutionalized ethical atrocities—such as chattel slavery, feudal serfdom, patriarchy, apartheid, and colonial exploitation—normalizing them through legal codes, cultural traditions, and moral rationalizations. Critical thinkers possess a heightened moral sensitivity that enables them to recognize the profound inhumanity embedded within socially accepted norms. Driven by an ethical commitment to human dignity, justice, and universal moral worth, critical thinkers confront these normalized injustices even at high personal cost.\n\nThe moral evolution of human civilization is directly attributable to critical thinkers who refused to align their personal ethics with the legal and cultural norms of their era. Figures like Harriet Tubman, Martin Luther King Jr., Nelson Mandela, and Malala Yousafzai recognized that legality does not equate to morality. By actively disobeying unjust laws and critiquing the ethical bankruptcy of the status quo, they catalyzed global shifts in moral consciousness. Their critiques forced societies to re-examine their ethical frameworks, leading to the abolition of slavery, the dismantling of legal segregation, the expansion of women's suffrage, and the codification of international human rights law.\n\nFurthermore, the evolution of human rights is an unfinished project that requires continuous critical scrutiny. Existing legal and moral frameworks often contain significant blind spots regarding emerging forms of oppression, such as digital surveillance, environmental degradation, corporate exploitation, and marginalization based on gender or ethnicity. Critical ethicists continuously push the boundaries of moral consideration, expanding human rights discourses to include future generations, non-human entities, and marginalized sub-populations. By maintaining a relentless critique of current ethical standards, critical thinkers ensure that moral philosophy remains dynamic, inclusive, and responsive to human suffering."
                    },
                    {
                        "heading": "Socio-Economic Stratification and Equity Advocacy",
                        "explanation": "Socio-economic systems across human history have consistently produced disparities in wealth, power, resource allocation, and social mobility. The status quo in stratified societies typically serves the material interests of economic elites, who utilize their resources to shape legislative agendas, control media apparatuses, and structure economic policies to perpetuate their wealth accumulation. Critical thinkers scrutinize these economic structures, exposing the systemic mechanisms—such as regressive taxation, labor exploitation, predatory financialization, and unequal access to capital—that generate and sustain structural inequality.\n\nTheoretical frameworks developed by economic critical thinkers, from Karl Marx's critique of political economy to contemporary analyses by Thomas Piketty and Amartya Sen, provide structural diagnostics of how capital accumulation reproduces class divides. These scholars demonstrate that economic stratification is not the result of individual moral failings or natural market forces, but rather the consequence of deliberate policy choices, legal frameworks, and structural arrangements. By demystifying the mechanisms of economic exploitation, critical thinkers equip social movements with the conceptual tools needed to advocate for progressive taxation, universal healthcare, public education, fair labor standards, and redistributive policies.\n\nMoreover, critical thinkers highlight the intersectional nature of socio-economic inequality, illustrating how class exploitation overlaps with racial, gender, and geographic marginalization. In developing nations and global south contexts, critical economists challenge global financial architectures and imperialist trade relations that keep post-colonial nations in conditions of economic dependency. By challenging both domestic and international economic orthodoxies, critical thinkers advocate for economic models that prioritize human well-being, ecological sustainability, and equitable wealth distribution over unbridled corporate profit and elite capital consolidation."
                    },
                    {
                        "heading": "Intellectual Liberty and the Evolution of Democratic Thought",
                        "explanation": "The preservation of intellectual liberty is both a primary prerequisite for, and a major objective of, challenging the status quo. Dominant political regimes and authoritarian systems routinely attempt to enforce ideological conformity by censoring dissenting viewpoints, restricting press freedom, and persecuting intellectual dissidents. Critical thinkers stand as guardians of intellectual liberty, asserting the fundamental right of individuals to question authority, express unconventional ideas, and participate in public deliberation. Their willingness to exercise freedom of thought in the face of authoritarian pressure creates the democratic space necessary for open public discourse.\n\nThe development of democratic theory is inextricably linked to the historical struggle for intellectual liberty. Thinkers such as John Stuart Mill, in his seminal work 'On Liberty', argued that suppressing dissenting opinions—even those universally considered false or dangerous—robs society of the opportunity to validate or refine truth through vigorous debate. Democratic governance relies on the institutionalization of dissent, recognizing that healthy political communities require continuous critique to identify policy failures, corruption, and systemic defects. Critical thinkers protect this democratic vitality by resisting state censorship, academic suppression, and social conformity.\n\nIn the contemporary digital era, threats to intellectual liberty have taken on novel, complex forms, including algorithmic echo chambers, state-sponsored disinformation, digital surveillance, and public cancel culture. Critical thinkers actively examine these new dynamics, warning against subtle forms of cognitive manipulation and ideological polarization that undermine democratic decision-making. By defending open inquiry, critical literacy, and robust public debate, critical intellectuals ensure that democratic societies retain their capacity for self-correction, ideological renewal, and inclusive political participation."
                    }
                ],
                "diagram_prompt": "A clean, minimal, 2D vector educational flowchart diagram on a solid white background illustrating the historical cycle of critical inquiry challenging the status quo. Horizontal flow with 5 rounded rectangular boxes connected by sharp arrows: '1. Hegemonic Status Quo Established' -> '2. Critical Inquiry & Structural Critique' -> '3. Epistemological & Social Disruption' -> '4. Institutional Adaptation & Reform' -> '5. Higher-Order Social Equilibrium'. Minimalist design, professional palette with dark blue and teal accents, clear typography, dark text, high clarity, no 3D rendering.",
                "conclusion": "In conclusion, critical thinkers challenge the status quo because civilizational progress, human rights, epistemological truth, and social justice depend fundamentally on the continuous destabilization of dogmatic authority and structural inequality. By exposing the historical contingency of power structures, resisting institutional inertia, confronting ethical failures, and defending intellectual liberty, critical thinkers serve as the essential conscience and corrective engine of human societies. Without their courageous interventions, civilizations inevitably stagnate into authoritarianism, economic exploitation, and cognitive decay; with their contributions, human societies maintain the capacity for continuous self-correction, democratic renewal, and moral evolution."
            },
            {
                "question_number": 2,
                "question_text": "Why is critical and reflective thinking important for teachers’ professional growth and development?",
                "introduction": "In the field of modern education, the role of the teacher has evolved far beyond the traditional paradigm of a passive transmitter of standardized knowledge. Contemporary educational environments are characterized by profound demographic diversity, complex socio-economic realities, rapid technological integration, and constantly shifting pedagogical mandates. In this dynamic context, professional competence cannot be achieved through the mechanical application of pre-packaged instructional materials or unreflective adherence to routine teaching methods. Instead, sustainable professional growth and development demand that teachers cultivate advanced capacities for critical and reflective thinking, transforming their practice into an ongoing process of intellectual inquiry, self-diagnostic evaluation, and pedagogical innovation.\n\nReflective thinking, as foundational educational theorist John Dewey articulated, involves the active, persistent, and careful consideration of any belief or supposed form of knowledge in light of the grounds that support it and the further conclusions to which it tends. When applied to education, reflective practice enables teachers to systematically analyze their instructional decisions, classroom interactions, assessment outcomes, and philosophical assumptions. Critical thinking extends this reflection further by embedding it within an awareness of broader socio-political structures, power dynamics, equity issues, and institutional constraints. Together, critical and reflective thinking empower educators to transition from technical executors of external directives to autonomous, professional decision-makers who actively shape learning environments to meet the diverse needs of their students.\n\nFurthermore, the integration of critical and reflective practice is essential for preventing professional burnout, pedagogical stagnation, and teacher attrition. When educators engage in continuous metacognition—thinking about their own thinking and practice—they develop professional agency, emotional resilience, and an adaptive expertise that allows them to navigate classroom challenges effectively. Critical reflective practice transforms classroom teaching into a rich laboratory for professional learning, where every lesson, student interaction, and instructional hurdle becomes an opportunity for actionable research and professional growth. Ultimately, fostering critical reflective thinking among teachers is the cornerstone of sustainable educational reform and elevated student achievement.",
                "sections": [
                    {
                        "heading": "Deconstructing Pedagogical Assumptions and Implicit Bias",
                        "explanation": "Every teacher enters the classroom carrying a complex matrix of personal beliefs, cultural values, socio-economic backgrounds, and implicit biases formed through their own schooling experiences and social conditioning. Unexamined assumptions regarding student intelligence, language background, behavioral norms, and learning capabilities frequently lead to equitable deficit-thinking patterns and lower expectations for marginalized student populations. Critical reflective thinking requires teachers to systematically examine and deconstruct these deeply ingrained assumptions, uncovering how their personal subjectivities influence their instructional choices, disciplinary actions, and relational dynamics with students.\n\nBy engaging in critical self-reflection, educators become aware of their implicit biases and how these biases manifest in classroom management and academic evaluation. For instance, a teacher might reflect on why they call on certain students more frequently than others, or why specific behavioral traits are interpreted as disruptive rather than expressive. Through critical frameworks like Culturally Responsive Pedagogy, developed by scholars like Gloria Ladson-Billings, reflective teachers actively unlearn discriminatory practices and restructure their instructional strategies to honor and leverage the diverse cultural assets that students bring to the learning environment.\n\nDeconstructing pedagogical assumptions also entails interrogating traditional views regarding intelligence, achievement, and learning styles. Unreflective teaching often defaults to standardized, one-size-fits-all instructional models that privilege linear, linguistic, or mathematical-logical ways of knowing while penalizing creative, oral, or kinesthetic modalities. Critical reflective practice prompts teachers to question these standardized norms, fostering inclusive instructional designs that accommodate neurodiversity, multilingualism, and varied learning trajectories, thereby creating a truly equitable learning ecosystem."
                    },
                    {
                        "heading": "Enhancing Action Research and Evidence-Based Practice",
                        "explanation": "Professional growth in teaching is fundamentally rooted in the ability to generate, analyze, and apply empirical evidence directly within the classroom context. Critical and reflective thinking transforms teachers into practitioner-researchers who do not merely consume educational research published by external experts, but actively conduct action research in their own classrooms. Action research involves identifying a classroom issue, formulating targeted instructional interventions, systematically gathering qualitative and quantitative data, reflecting on the outcomes, and iteratively refining instructional practices to optimize student learning.\n\nEngaging in action research requires a high level of critical thinking, as teachers must select appropriate diagnostic tools, analyze student work samples, interpret performance data, and evaluate the effectiveness of their pedagogical strategies. Rather than relying on intuition, anecdotal impressions, or unverified instructional trends, reflective teachers ground their decision-making in concrete evidence collected from their specific context. This empirical orientation ensures that teaching methodologies are continuously calibrated to address demonstrated student learning gaps and emerging educational challenges.\n\nFurthermore, action research bridges the long-standing divide between educational theory and real-world classroom application. When teachers critically reflect on the outcome of an instructional experiment, they generate localized, contextualized pedagogical knowledge that contributes to the broader professional learning community. This systematic inquiry elevates teaching from a routine technical craft to an evidence-based professional discipline, enabling educators to articulate and justify their instructional choices to colleagues, administrators, and parents with authority and clarity."
                    },
                    {
                        "heading": "Fostering Adaptive Expertise and Differentiated Instruction",
                        "explanation": "Classroom environments are inherently unpredictable, non-linear, and complex spaces where static instructional plans frequently encounter unforeseen obstacles. Teachers who lack critical reflective skills often display rigid adherence to lesson plans, struggling to respond effectively when students exhibit misunderstanding or disengagement. In contrast, critical reflective thinking develops adaptive expertise—the ability to flexibly apply core pedagogical principles to novel, dynamic, and challenging classroom situations, adjusting instruction in real-time based on continuous formative feedback.\n\nAdaptive expertise is essential for implementing meaningful differentiated instruction. Modern classrooms comprise students with vastly different pre-existing knowledge bases, language proficiencies, cognitive processing speeds, and socio-emotional needs. Reflective teachers continuously monitor student comprehension through observational analysis, questioning strategies, and formative assessment data, critically evaluating which aspects of a lesson are working and which require immediate adaptation. This real-time reflection allows teachers to scaffold content, alter instructional pacing, and modify learning activities to support diverse learners simultaneously.\n\nMoreover, adaptive expertise enables teachers to effectively navigate unexpected instructional disruptions or teachable moments. When a student poses an unforeseen, profound question or when a technology failure interrupts a planned activity, reflective teachers quickly evaluate alternative pedagogical pathways, turning potential disruptions into valuable learning opportunities. This pedagogical agility fosters an engaging, responsive, and dynamic classroom climate where learning is prioritized over strict procedural compliance."
                    },
                    {
                        "heading": "Bridging Theoretical Paradigms and Classroom Reality",
                        "explanation": "Teacher preparation programs and professional development seminars expose educators to a vast array of theoretical frameworks, learning theories (such as behaviorism, cognitivism, constructivism, and socio-cultural theory), and methodological approaches. However, a common crisis in teacher education is the 'theory-practice gap,' where teachers struggle to operationalize abstract theoretical concepts within the high-pressure, resource-constrained realities of everyday classroom teaching. Critical and reflective thinking acts as the indispensable bridge that connects theoretical knowledge with concrete instructional practice.\n\nReflective teachers do not view theory as a set of rigid, universal rules to be blindly executed; rather, they treat theory as an analytical lens through which classroom dynamics can be understood, interpreted, and managed. For instance, a teacher grounded in Lev Vygotsky's Zone of Proximal Development (ZPD) uses critical reflection to evaluate whether assigned tasks are located within students' developmental reach and whether adequate instructional scaffolding is being provided. Through continuous reflection, the teacher translates the theoretical construct of ZPD into concrete classroom practices like peer tutoring, graphic organizers, and guided questioning.\n\nAdditionally, critical reflection allows teachers to interrogate and critique educational theories themselves, recognizing that theoretical models created in specific research contexts may not apply directly to their localized cultural or socio-economic settings. By critically evaluating how theories perform in actual practice, teachers refine their personal theories of teaching, synthesizing formal research with practical wisdom to construct robust, context-sensitive instructional frameworks that maximize pedagogical effectiveness."
                    },
                    {
                        "heading": "Cultivating Professional Autonomy and Teacher Agency",
                        "explanation": "In many contemporary educational systems, teachers face increasing pressures from top-down administrative mandates, standardized testing regimes, scripted curricula, and prescriptive accountability frameworks. These forces risk de-professionalizing teaching, reducing educators to compliant technicians who execute pre-determined instructional routines without professional discretion. Critical and reflective thinking serves as a vital safeguard for teacher agency and professional autonomy, empowering educators to advocate for sound pedagogical practices rooted in the genuine needs of their students.\n\nWhen teachers are critical thinkers, they do not passively accept top-down directives or commercial curricular packages without rigorous evaluation. Instead, they critically analyze policy mandates, standardized metrics, and instructional programs, assessing their validity, developmental appropriateness, and alignment with equitable educational principles. When policies or standardized materials conflict with optimal student learning, reflective teachers exercise professional agency by modifying, supplementing, or adapting the curriculum to protect student well-being and academic integrity.\n\nFurthermore, teacher agency fostered by reflective practice extends beyond individual classrooms into institutional decision-making and policy discourse. Critical reflective educators articulate coherent, evidence-based arguments during faculty meetings, curriculum development committees, and professional organizations. They transform from passive recipients of educational reform into active agents of institutional change, influencing school culture, professional development priorities, and community engagement strategies to reflect progressive, student-centered values."
                    },
                    {
                        "heading": "Nurturing a Culture of Continuous Metacognitive Growth",
                        "explanation": "Professional development is not a static milestone achieved upon earning a teaching credential; rather, it is a lifelong process of continuous learning, self-assessment, and personal evolution. Without ongoing critical reflection, even experienced teachers risk falling into cognitive complacency, relying indefinitely on outdated instructional methods, stale course materials, and unexamined routines. Critical reflective thinking nurtures a culture of continuous metacognition, ensuring that professional growth remains an active, permanent priority throughout an educator's career.\n\nMetacognitive growth involves developing a heightened awareness of one's own cognitive processes, instructional strengths, and professional limitations. Reflective teachers regularly engage in structured self-evaluation practices, such as maintaining reflective journals, recording and analyzing video recordings of their classroom instruction, and inviting peer observations and constructive feedback from colleagues. By exposing their practice to rigorous self-scrutiny and collaborative review, teachers identify specific areas for professional enhancement, setting targeted goals for continuous skill acquisition.\n\nMoreover, a commitment to metacognitive growth models lifelong learning for students. When students observe their teachers engaging in self-reflection, admitting errors, seeking continuous improvement, and demonstrating curiosity, they internalize these behaviors as essential attributes of successful learners. In this way, critical reflective practice creates a reciprocal learning culture within the classroom and the broader school community, elevating collective educational quality and sustaining lifelong professional excellence."
                    }
                ],
                "diagram_prompt": "A clean, minimal, 2D vector educational flowchart diagram on a solid white background illustrating the reflective teaching cycle for continuous professional growth. Circular/cyclic flow with 5 rounded rectangular boxes connected by curved sharp arrows: '1. Concrete Teaching Experience' -> '2. Reflective Observation & Data Collection' -> '3. Critical Analysis & Theoretical Linking' -> '4. Re-formulation of Pedagogical Strategy' -> '5. Active Experimentation in Classroom'. Minimalist design, professional navy and amber color palette, dark text, high clarity, no 3D rendering.",
                "conclusion": "In summary, critical and reflective thinking is the fundamental cornerstone of meaningful teacher professional growth and development. By systematically deconstructing pedagogical assumptions, conducting evidence-based action research, developing adaptive expertise, bridging theoretical concepts with classroom practice, asserting professional agency, and committing to lifelong metacognition, teachers transcend technical instruction to become master practitioners. Cultivating reflective educators ultimately ensures that school environments remain intellectually vibrant, culturally responsive, equity-driven, and highly effective in fostering deep, transformative student learning."
            },
            {
                "question_number": 3,
                "question_text": "How do you see the theories of Paulo Freire and Pierre Bourdieu applicable in Pakistan?",
                "introduction": "The sociological and pedagogical landscapes of Pakistan present a complex tapestry of deep socio-economic stratification, linguistic divides, institutional hierarchies, and entrenched power dynamics. In analyzing these structural challenges, the theoretical frameworks of Brazilian educator Paulo Freire and French sociologist Pierre Bourdieu provide extraordinarily sharp critical lenses. Freire’s critical pedagogy—centered on the critique of 'banking education,' the necessity of 'conscientization' (critical consciousness), and humanizing dialogue—directly confronts patriarchal, authoritarian, and rote-learning instruction prevalent in developing educational systems. Simultaneously, Bourdieu’s sociological concepts of 'cultural capital,' 'habitus,' 'field,' and 'symbolic violence' elucidate how educational institutions quietly reproduce existing class structures, converting socio-economic privilege into institutionalized academic merit.\n\nIn the context of Pakistan, education operates within a starkly multi-tiered system divided along social, economic, and linguistic lines. Elite private English-medium schools, semi-funded state schools, low-cost private institutions, and traditional religious seminaries (Madaris) cater to distinct socio-economic classes, delivering radically different qualities of education and cultural orientation. Bourdieu’s theory of cultural capital explains how the upper classes utilize English linguistic proficiency, Westernized social manners, and elite networking opportunities to secure dominant positions in the civil service, corporate sector, and political arenas, while lower-income students are systematically marginalized due to their lack of institutionalized cultural capital. Education in Pakistan thus acts less as a vehicle for social mobility and more as an apparatus for class reproduction.\n\nConcurrently, Freire’s analysis of banking education mirrors the dominant instructional methodologies found across most public and low-cost private schools in Pakistan. Learning is widely characterized by passive memorization, rigid adherence to prescribed textbooks, high-stakes examination regimes, and authoritarian teacher-student dynamics that discourage critical inquiry, questioning, and social reflexivity. By synthesizing Freire’s call for liberating, problem-posing education with Bourdieu’s structural diagnostic of social reproduction, Pakistani educators and policy makers can uncover the root causes of educational inequality and formulate transformative, culturally grounded reforms that empower marginalized communities across the country.",
                "sections": [
                    {
                        "heading": "Cultural Capital and Class Reproduction in Pakistani Schooling",
                        "explanation": "Pierre Bourdieu’s theory of cultural capital posits that non-economic assets—such as linguistic fluency, cultural background, behavioral styles, and educational credentials—play a decisive role in determining an individual's social mobility and status. In Pakistan, cultural capital is highly institutionalized and unequally distributed, primarily along the divide between English-medium and Urdu-medium or regional-language schooling environments. Elite private schools (such as Cambridge-track institutions) equip students from wealthy backgrounds with fluent English, global cultural literacy, and social confidence, which are highly valued by university admissions boards, multinational corporations, and state institutions.\n\nConversely, students attending under-resourced public schools or low-cost private institutions acquire cultural capital that is consistently devalued by the dominant social field. Despite possessing equal innate intellectual ability, working-class and rural students often struggle to access prestigious higher education programs or high-paying employment opportunities because their linguistic repertoire and social manners do not conform to elite expectations. Bourdieu’s model demonstrates that this outcome is not a reflection of individual merit, but rather an institutional mechanism that validates elite cultural habits while penalizing those of working-class background.\n\nThus, the Pakistani education system functions as an agent of class reproduction, ensuring that economic privilege is successfully converted into legitimate educational credentials across generations. Elite families utilize their material wealth to purchase high-status cultural capital for their children, effectively locking in social advantages and preserving elite hegemony. Bourdieu’s analytical framework provides Pakistani researchers with a powerful tool to expose how current school structures naturalize social privilege and perpetuate structural inequality under the guise of academic meritocracy."
                    },
                    {
                        "heading": "Banking Education versus Critical Pedagogy in Local Contexts",
                        "explanation": "Paulo Freire’s critique of 'banking education' describes an instructional paradigm wherein students are treated as empty, passive receptacles into which teachers deposit standardized, unexamined knowledge. This model is acutely prevalent throughout Pakistan’s national and provincial educational landscape. In the vast majority of primary and secondary schools, instruction centers on 'rote learning' (locally termed 'Ratta system'), where success is measured solely by a student's capacity to memorize textbook content and reproduce it verbatim during standardized board examinations. Critical questioning, independent analysis, and creative problem-solving are actively discouraged or penalized within this authoritarian structure.\n\nFreire argued that banking education is inherently dehumanizing and oppressive, as it conditions learners to accept authority uncritically, internalize passivity, and adapt to existing social inequalities rather than questioning them. In Pakistan, this pedagogical approach produces generations of graduates who may possess formal certificates but lack the critical thinking capacity to analyze complex socio-political challenges, interrogate corrupt governance structures, or innovate within the economy. The classroom dynamics mirror and reinforce the authoritarian, patriarchal structures of broader Pakistani society, suppressing independent thought and civic agency.\n\nImplementing Freire’s alternative— critical pedagogy and 'problem-posing education'—offers a revolutionary pathway for Pakistani classrooms. Problem-posing education positions teachers and students as co-investigators of reality, replacing monologue with dialogue and textbook memorization with critical reflection on local conditions. By encouraging Pakistani students to analyze real-world issues—such as water scarcity, local governance failures, poverty, and gender inequality—schools can transform into vibrant spaces of critical inquiry, producing active citizens who are empowered to transform their local communities."
                    },
                    {
                        "heading": "Linguistic Hegemony and Symbolic Violence in Curriculum",
                        "explanation": "Bourdieu’s concept of 'symbolic violence' describes the subtle, non-physical forms of domination wherein marginalized groups internalize the cultural norms of dominant elites, coming to view their own exclusion as natural, legitimate, or deserved. In Pakistan, symbolic violence manifests most potently through linguistic hegemony. English is established as the official language of power, higher education, governance, and the judiciary, despite being spoken fluently by only a small minority of the elite population. Concurrently, native regional languages (such as Punjabi, Pashto, Sindhi, Balochi, and Saraiki) are marginalized within formal schooling contexts.\n\nWhen children from non-English speaking households enter schools where English or formal standard Urdu is mandated as the sole medium of instruction, their native linguistic heritage and prior knowledge are devalued. Students experience cognitive distress, academic failure, and a deep sense of cultural inferiority, internalizing the belief that their native languages and cultural identities are inherently inferior or unsuitable for intellectual pursuits. Bourdieu highlights this process as classic symbolic violence: the institution inflicts psychological harm by delegitimizing the student's primary cultural capital, forcing them to accept the superiority of elite language codes.\n\nApplying this theory to Pakistani curricular policy demonstrates the urgent need for mother-tongue-based multilingual education (MTB-MLE). Recognizing local languages within primary education restores dignity to marginalized communities, enhances early cognitive development, and mitigates symbolic violence. By dismantling linguistic hegemony, Pakistan can build an educational system that validates the socio-cultural backgrounds of all students, fostering equitable learning environments and preserving the country’s rich linguistic heritage."
                    },
                    {
                        "heading": "Habitus and Educational Aspirations Across Social Strata",
                        "explanation": "Bourdieu defined 'habitus' as a set of deeply internalized, embodied dispositions, schemes of perception, and habitual behaviors shaped by an individual's socio-economic conditions and life experiences. Habitus operates beneath the conscious level, structuring what individuals perceive as reasonable, achievable, or 'for people like us.' In Pakistan, the habitus of students from different socio-economic backgrounds creates vastly different educational aspirations, horizons of expectation, and career trajectories long before they complete their schooling.\n\nStudents from affluent, educated urban families internalize a habitus that treats university education, international study, high-status professions, and leadership positions as natural, achievable expectations. Their home environment, filled with books, intellectual discourse, and professional role models, continuously reinforces these ambitions. In contrast, working-class, rural, or marginalized students often internalize a habitus constrained by economic precarity, limited local job prospects, and systemic discrimination. Consequently, lower-income students in Pakistan frequently self-eliminate from higher education options, believing that advanced academic success is reserved exclusively for the elite class.\n\nUnderstanding habitus allows Pakistani educators to see that low educational attainment in marginalized communities is not caused by a lack of intrinsic ambition, but by structural constraints that shape individual dispositions. Educational interventions cannot simply focus on expanding physical infrastructure; they must address the underlying socio-economic conditions and psychological barriers that constrain student habitus. Providing mentorship programs, community-based career guidance, and visible role models can help broaden the internal horizons of disadvantaged students, helping them overcome internalized limitations imposed by class stratification."
                    },
                    {
                        "heading": "Conscientization as a Catalyst for Structural Reform",
                        "explanation": "A central pillar of Freire’s theoretical framework is 'conscientization' (conscientização), which refers to the process by which individuals develop a critical awareness of social, political, and economic contradictions, learning to take action against the oppressive elements of their reality. In Pakistan, marginalized populations—such as rural agricultural workers, urban slum dwellers, religious minorities, and working-class women—often experience profound structural disenfranchisement, exacerbated by low literacy rates and limited political representation. Conscientization offers a methodology for empowering these communities through transformative education.\n\nTraditional adult literacy programs in Pakistan have largely focused on functional literacy—teaching basic reading and writing skills in isolation from students' social contexts. Freire strongly critiqued this functional approach, arguing that literacy must be deeply tied to political awareness and social liberation. Applying Freirean adult literacy methodologies in rural and peri-urban Pakistan involves using 'generative themes'—words and concepts derived from community members' daily struggles, such as land rights, clean water access, debt bondage, and health care. Through structured group dialogues (culture circles), participants analyze these themes, recognize that their suffering is structural rather than pre-ordained, and formulate collective strategies for advocacy.\n\nConscientization provides a powerful blueprint for civil society organizations, community schools, and non-governmental organizations operating in Pakistan. By integrating critical literacy and social diagnostic tools into non-formal and formal education programs, local initiatives can build grassroots leadership, empower women, and strengthen democratic participation. Conscientization transforms education into a tool for genuine community empowerment, driving structural reform from the bottom up."
                    },
                    {
                        "heading": "Institutional Policy Interventions for Educational Equity",
                        "explanation": "Synthesizing the theoretical insights of Freire and Bourdieu provides Pakistani educational planners with a clear blueprint for comprehensive institutional policy reform. Addressing the structural class reproduction identified by Bourdieu requires targeted policy measures that equalize the distribution of cultural and economic capital across the schooling sector. This includes implementing standardized resource allocations to public schools, modernizing public school infrastructure, improving teacher training programs, and ensuring equitable access to high-quality English language and digital literacy instruction for all students regardless of socio-economic background.\n\nSimultaneously, incorporating Freirean pedagogy demands a fundamental overhaul of national curriculum frameworks, pedagogical training, and assessment systems. Educational policies must move away from rigid, high-stakes examination models that incentivize rote memorization, replacing them with formative, inquiry-based assessment methods that evaluate critical thinking, problem-solving, and civic engagement. National textbook boards must redesign learning materials to include diverse socio-cultural perspectives, encouraging students to critically interrogate historical narratives, ecological issues, and social structures.\n\nFinally, policy interventions must actively dismantle the multi-tiered educational architecture that reinforces social segregation. Establishing common core standards, enforcing non-discriminatory admissions policies, and scaling up scholarship programs for underrepresented students are critical steps toward structural equity. By combining Bourdieu’s structural diagnostic with Freire’s pedagogical humanism, Pakistan can construct an inclusive, democratic educational system that fosters social mobility, critical citizenship, and national cohesion."
                    }
                ],
                "diagram_prompt": "A clean, minimal, 2D vector educational diagram on a solid white background contrasting Bourdieu's Class Reproduction with Freire's Critical Pedagogy in Pakistan. Two parallel horizontal tracks: Top Track (Bourdieu) showing 'Elite Capital & English Medium' -> 'Institutional Validation' -> 'Social Class Reproduction'. Bottom Track (Freire) showing 'Rote Banking System' -> 'Critical Conscientization' -> 'Transformative Social Liberation'. Minimalist vector style, sharp arrows, clear headers, contrasting navy blue and terracotta accents, high clarity, dark text, no 3D rendering.",
                "conclusion": "In conclusion, the theoretical paradigms of Paulo Freire and Pierre Bourdieu offer profound diagnostic and transformative utility for the Pakistani educational landscape. Bourdieu’s concepts of cultural capital, habitus, and symbolic violence systematically expose how Pakistan's multi-tiered educational system reproduces socio-economic inequality and preserves elite hegemony. Concurrently, Freire’s critique of banking education and model of conscientization provide an actionable framework for dismantling rote learning and empowering marginalized populations through critical, dialogic inquiry. By integrating these theoretical perspectives, Pakistani educational policy can shift from an instrument of class division to a powerful catalyst for equity, critical citizenship, and structural transformation."
            },
            {
                "question_number": 4,
                "question_text": "Think of your own learning experiences and write a critical review of classroom instructional practices in schools",
                "introduction": "Reflecting upon personal learning experiences within primary and secondary school systems reveals a landscape deeply defined by structural paradoxes, institutional rigidities, and traditional instructional paradigms. For many students who navigated standard public or low-cost private educational institutions, the dominant memory of schooling centers on passive compliance, repetitive textbook exercises, and relentless preparation for high-stakes examinations. While these instructional environments maintained order and systematically covered mandated syllabi, they frequently failed to ignite genuine intellectual curiosity, critical inquiry, or deep conceptual understanding. A critical review of personal educational experiences provides a valuable reflexive entry point to analyze broader systemic deficiencies in mainstream classroom practices.\n\nSchooling historically operated under a traditional, teacher-centered paradigm heavily influenced by behaviorist learning models. In these classrooms, knowledge was treated as a static, pre-packaged commodity to be transferred directly from the authoritative teacher into the passive minds of students. Classroom physical configurations—with desks arranged in rigid rows facing a central blackboard—symbolized and enforced this unidirectional flow of power and knowledge. Instructional practices prioritized behavioral compliance, silence, and uniform execution of tasks, leaving minimal space for collaborative learning, creative exploration, or personalized learning pathways tailored to diverse student needs.\n\nConducting a critical review of these lived educational experiences requires moving beyond individual nostalgia or personal grievances to examine how institutional policies, assessment metrics, teacher training deficits, and socio-cultural norms combined to shape classroom instruction. By evaluating core dimensions such as instructional methodologies, assessment regimes, classroom power dynamics, and technological integration through contemporary educational research, this review highlights the urgent necessity of transitioning from traditional, passive instructional models toward dynamic, student-centered, and constructivist learning environments.",
                "sections": [
                    {
                        "heading": "Rote Memorization versus Deep Conceptual Understanding",
                        "explanation": "A prominent characteristic of traditional classroom instruction, as personally experienced throughout primary and secondary schooling, is the overwhelming reliance on rote memorization. Lessons were predominantly structured around verbatim recall of textbook content, formulas, and historical facts. Instructional delivery typically involved teachers reading directly from prescribed textbooks, writing summary points on the blackboard, and directing students to copy and memorize the material for upcoming assessments. Deep conceptual understanding, critical analysis, and real-world contextual application were routinely bypassed in favor of surface-level memory retrieval.\n\nThis emphasis on rote learning fundamentally distorts the cognitive purpose of education. Educational taxonomy frameworks, such as Bloom's Revised Taxonomy, demonstrate that lower-order cognitive skills—such as remembering and understanding—occupy only the baseline of intellectual development. Higher-order cognitive processes, including applying, analyzing, evaluating, and creating, were rarely cultivated in the daily classroom routine. Consequently, students frequently achieved high test marks by memorizing definitions and procedures without comprehending the underlying principles, leading to rapid knowledge decay once examinations concluded.\n\nTo address this instructional deficit, contemporary schools must systematically pivot toward constructivist learning frameworks that prioritize deep conceptual understanding. Constructivist instruction engages students in active problem-solving, guided inquiry, and authentic learning tasks where they construct knowledge by connecting new concepts to prior experiences. Replacing passive memorization with interactive experiments, project-based learning, and analytical discussions equips students with enduring cognitive abilities and adaptable knowledge structures essential for real-world problem-solving."
                    },
                    {
                        "heading": "Teacher-Centred Dogmatism and Student Passivity",
                        "explanation": "Instructional practices in traditional classrooms were characterized by intense teacher-centered dogmatism, where the educator acted as the absolute, undisputed authority figure and sole source of knowledge. The pedagogical dialogue was almost exclusively unidirectional: teachers spoke, instructed, and evaluated, while students listened, recorded, and obeyed. Student participation was strictly bounded, limited to answering closed-ended questions designed to test recall rather than stimulate analytical debate. Questioning textbook authority, proposing alternative interpretations, or challenging a teacher's explanation was frequently discouraged or viewed as behavioral insolence.\n\nThis dogmatic structure fosters profound student passivity, intellectual dependency, and learned helplessness. When learners are consistently positioned as passive recipients rather than active participants in their own education, they lose the motivation to engage in self-directed inquiry or independent thinking. The classroom environment becomes a space of intellectual compliance rather than vibrant curiosity, suppressing natural cognitive exploration and creative risk-taking. Students adapt to the system by adopting a performative posture—doing only what is required to pass without genuine intellectual engagement.\n\nTransforming this authoritarian dynamic requires adopting student-centered pedagogical models, such as inquiry-based and dialogic learning. In a student-centered classroom, the teacher's role shifts from an authoritative instructor to a facilitator and co-investigator of learning. Classrooms are reorganized to encourage collaborative peer discussion, open inquiry, and student-led investigations. By validating student voices and encouraging critical questioning, educators cultivate autonomous learners who take active ownership of their intellectual development."
                    },
                    {
                        "heading": "Assessment Regimes and the Washback Effect",
                        "explanation": "Personal reflection on school instructional practices highlights the complete dominance of high-stakes, summative assessment regimes. Schooling was almost entirely driven by high-stakes terminal examinations, standardized testing, and numerical rankings. These assessment structures created a powerful 'washback effect'—a phenomenon where the format and content of national tests dictate classroom instructional practices, narrowing the curriculum strictly to what is testable on end-of-year exams.\n\nBecause standardized tests heavily privileged rote recall and standardized answer formats, teachers understandably tailored their daily instruction to 'teach to the test.' Classroom time was consumed by drill-and-practice exercises, memorizing past paper solutions, and learning exam-taking tricks rather than exploring topics in depth or developing critical thinking skills. Subjects or competencies not directly evaluated on standardized exams—such as creative writing, practical scientific inquiry, artistic expression, and socio-emotional learning—were marginalized or eliminated from the curriculum entirely.\n\nTo overcome the harmful consequences of exam-driven washback, educational systems must implement comprehensive, balanced assessment practices that emphasize formative assessment for learning. Formative assessments—such as reflective learning portfolios, peer evaluations, self-assessments, and authentic performance tasks—provide ongoing, constructive feedback that supports continuous student growth. Shifting focus from summative evaluation to formative guidance transforms assessment into an empowering educational tool rather than a source of chronic anxiety and curricular narrowing."
                    },
                    {
                        "heading": "Exclusionary Practices and Classroom Diversity Challenges",
                        "explanation": "A critical review of historical classroom practices reveals a widespread failure to accommodate student diversity in learning styles, cognitive processing speeds, linguistic backgrounds, and physical or neurodivergent needs. Traditional instruction operated under the flawed assumption of a 'homogenous average student.' Curricula, instructional speeds, and teaching styles were standardized, leaving students who deviated from this arbitrary norm at a severe academic and socio-emotional disadvantage.\n\nIn practice, this standardization produced exclusionary outcomes. Students who required additional time, visual or kinesthetic learning modalities, or differentiated language support were often labeled as low achievers or academically unfit. Conversely, highly advanced students experienced chronic disengagement due to a lack of intellectual challenge. Furthermore, socio-cultural, gender, and economic diversities were rarely acknowledged or integrated into instructional design, resulting in culturally disconnected learning experiences for students from marginalized backgrounds.\n\nOvercoming these exclusionary patterns requires embedding Universal Design for Learning (UDL) principles and differentiated instruction into core teaching practices. UDL frameworks mandate that teachers provide multiple means of engagement, representation, and action/expression, ensuring that instructional content is accessible to all learners regardless of their background or neurotype. Recognizing classroom diversity as an enriching asset rather than an instructional hurdle fosters an inclusive, equitable educational environment where every student can thrive."
                    },
                    {
                        "heading": "Technological Integration Gaps and Pedagogical Inertia",
                        "explanation": "Reflecting on school experiences exposes a substantial gap between technological advancement in wider society and its meaningful integration within classroom instruction. Where digital technologies were present in schools, their utilization was typically superficial, passive, or administrative. Computers and digital projectors were often used merely to display static presentation slides or electronic textbooks, leaving underlying teacher-centered, passive instructional methods completely unchanged.\n\nThis gap stems from pedagogical inertia—a resistance within institutional schooling to adapt teaching methods to leverage the transformative potential of modern technology. Simply placing digital hardware into classrooms without reforming pedagogical strategies fails to enhance student learning outcomes. When technology is integrated without a clear pedagogical purpose, it serves merely as an expensive substitute for traditional chalkboards, failing to cultivate modern digital literacy, computational thinking, or collaborative research skills among students.\n\nTo achieve authentic technological integration, schools must adopt frameworks such as the TPACK (Technological Pedagogical Content Knowledge) model, which emphasizes the seamless alignment of technology, pedagogy, and subject-matter content. Meaningful digital integration empowers students to engage in collaborative online research, simulation modeling, digital content creation, and global peer interaction. By leveraging technology to support active, constructivist learning, schools can bridge the gap between classroom instruction and the technological demands of the modern world."
                    },
                    {
                        "heading": "Reformative Pathways Toward Student-Centred Learning",
                        "explanation": "Synthesizing personal schooling reflections and critical educational analysis highlights an urgent imperative for structural pedagogical reform. Moving away from traditional, authoritarian, and rote-learning instruction requires a holistic transformation encompassing initial teacher education, continuous professional development, curricular design, and institutional culture. Schools must shift from passive knowledge-transmission centers into dynamic communities of active inquiry, collaboration, and critical reflection.\n\nReforming instructional practice begins with comprehensive professional development that equips teachers with constructivist, student-centered teaching methodologies. Educators must be trained to design problem-based learning units, facilitate dialogic classroom discussions, utilize formative diagnostic tools, and manage collaborative learning environments effectively. Furthermore, school leadership and administrative frameworks must support instructional innovation, providing teachers with the pedagogical autonomy, collaborative planning time, and physical resources required to transform their classrooms.\n\nUltimately, student-centered learning environments nurture self-directed, intrinsically motivated, and critically conscious individuals. By prioritizing active inquiry, deep conceptual understanding, inclusive practices, and authentic assessment, reformed educational systems can prepare students not merely to pass standardized examinations, but to navigate complex real-world challenges, contribute meaningfully to society, and engage in lifelong intellectual growth."
                    }
                ],
                "diagram_prompt": "A clean, minimal, 2D vector educational comparison flowchart diagram on a solid white background contrasting Traditional vs. Reformed Classroom Instructional Practices. Two side-by-side vertical blocks: Left Block (Traditional) with 4 rounded steps: 'Teacher-Centred Monologue' -> 'Rote Memorization' -> 'Summative High-Stakes Exams' -> 'Passive Student Compliance'. Right Block (Reformed) with 4 rounded steps: 'Student-Centred Facilitation' -> 'Deep Conceptual Inquiry' -> 'Formative Authentic Assessment' -> 'Active Critical Agency'. Minimalist design, clean typography, dark text, blue and orange color highlights, no 3D rendering.",
                "conclusion": "In conclusion, a critical review of personal school learning experiences underscores the systemic limitations of traditional, teacher-centered, and rote-based instructional practices. The reliance on memorization, authoritarian classroom management, exam-driven washback, and standardized instruction has historically suppressed student agency, critical inquiry, and deep conceptual learning. Reimagining school instruction requires a decisive structural shift toward constructivist, student-centered, and inclusive pedagogical models that embrace technology, honor learner diversity, and cultivate critical thinking, thereby preparing students for meaningful engagement in a complex world."
            },
            {
                "question_number": 5,
                "question_text": "How do you see the learners of this generation different from all previous generations?",
                "introduction": "The contemporary generation of learners—often designated as Generation Z and Generation Alpha—occupies a historically unique position in human development. Born into a fully hyper-connected, digitized, and algorithmically mediated world, these learners have never known an era without pervasive high-speed internet, mobile computing, social media platforms, and instant information access. Unlike all preceding generations, for whom information was scarce, centralized, and mediated primarily through physical print, broadcast media, and institutional authority figures, today's learners are immersed in a continuous, ubiquitous data stream. This profound shift in the technological and information landscape has fundamentally altered cognitive processing, socio-emotional development, learning preferences, and cultural orientations among contemporary youth.\n\nThis technological saturation has rewired how learners engage with knowledge, authority, and communication. Traditional educational models were constructed on the assumption that schools held a monopoly on knowledge, and teachers served as the primary gatekeepers of information. For contemporary learners, this paradigm is obsolete; information on virtually any topic is instantly accessible via a smartphone search or AI interface. Consequently, the core educational challenge for this generation has shifted from accessing information to critically evaluating, synthesizing, and applying vast quantities of complex, multi-modal data. Furthermore, their continuous exposure to interactive, visually rich digital environments has shaped distinct cognitive traits, including heightened visual-spatial processing abilities, a demand for immediate feedback, and a preference for non-linear, self-directed learning experiences.\n\nHowever, these generational distinctions extend far beyond digital technology. Contemporary learners are developing consciousness amidst unprecedented global challenges, including accelerated climate change, economic volatility, political polarization, and widespread socio-political activism. These realities have produced a generation characterized by acute socio-political awareness, a demand for authenticity and inclusivity, and a deep-seated desire for education that demonstrates immediate real-world relevance. Understanding how today's learners differ from previous generations is an urgent prerequisite for modernizing educational systems, revising pedagogical practices, and designing learning environments that effectively support 21st-century youth.",
                "sections": [
                    {
                        "heading": "Digital Nativism and Cognition in the Information Age",
                        "explanation": "Contemporary learners are the first true 'digital natives'—individuals who have interacted with digital interfaces, touchscreen devices, and online network structures from early infancy. This immersive exposure has generated distinct neuro-cognitive processing patterns that differentiate them sharply from 'digital immigrants' of older generations. While previous generations developed linear, sequential information-processing habits through extensive reading of continuous print text, today’s learners process information non-linearly, navigating fluidly across hyperlinked, multi-modal, and interactive media formats.\n\nThis cognitive orientation manifests in exceptional visual-spatial literacy and rapid perceptual processing speeds. Modern learners excel at decoding complex visual data, graphic interfaces, and video content, often understanding multi-layered visual information much faster than linear written text. However, this shift presents cognitive trade-offs: extensive exposure to short-form, high-stimulation digital media can hinder the development of deep, sustained attention required for reading long-form text and performing prolonged analytical tasks without external stimulation.\n\nFor educators, digital nativism requires a shift from traditional text-heavy instruction to dynamic, multi-modal teaching strategies. Instructional design must incorporate interactive digital simulations, multimedia presentations, and collaborative online platforms to engage modern learners effectively. Simultaneously, schools must explicitly teach deep reading, sustained focus, and cognitive stamina, helping digital natives balance rapid visual processing with the continuous attention required for complex scholarly inquiry."
                    },
                    {
                        "heading": "Hyper-Connectedness and Shifts in Socio-Emotional Dynamics",
                        "explanation": "The pervasive presence of global social media networks and messaging platforms has fundamentally transformed the social and emotional development of contemporary learners. Unlike previous generations, whose social interactions were bounded by physical geography, neighborhood proximity, and school hours, modern learners maintain continuous, hyper-connected digital relationships. This 24/7 connectivity expands their social reach and access to global peer communities, but it also exposes them to constant peer surveillance, online social comparison, and cyberbullying.\n\nConsequently, contemporary learners exhibit unique socio-emotional vulnerabilities, including elevated rates of anxiety, depression, fear of missing out (FOMO), and social fatigue. The pressure to curate a optimized digital persona across multiple platforms introduces psychological stressors unknown to previous generations. Furthermore, reliance on text-based and algorithmic digital communication can sometimes impede the development of nuanced face-to-face interpersonal skills, active listening, and non-verbal emotional decoding.\n\nEducational institutions must respond to these socio-emotional shifts by integrating comprehensive Social-Emotional Learning (SEL) programs and digital wellness instruction into the core curriculum. Schools must serve as safe spaces where learners develop emotional resilience, healthy online boundaries, empathy, and meaningful face-to-face communication skills. Supporting the socio-emotional well-being of hyper-connected learners is an essential prerequisite for academic success and healthy psychological development."
                    },
                    {
                        "heading": "Multitasking, Attention Spans, and Information Processing Patterns",
                        "explanation": "A defining characteristic of contemporary learners is their habit of continuous media multitasking—simultaneously monitoring social media notifications, streaming audio or video, messaging peers, and attempting to complete academic tasks. While previous generations typically focused on single tasks sequentially, modern learners operate in continuous partial attention environments, rapidly switching focus between multiple digital streams.\n\nCognitive psychology research demonstrates that true cognitive multitasking is a myth; the brain rapidly switches focus between tasks, incurring a 'cognitive switching cost' that reduces working memory capacity, increases error rates, and hinders deep learning consolidation. Consequently, while contemporary learners demonstrate high speed in surface-level task switching, their sustained attention span for static, low-stimulation tasks (such as listening to a continuous 60-minute lecture) has significantly decreased compared to prior generations.\n\nTo optimize learning for this cognitive profile, educators must restructure instructional pacing and delivery. Long, unbroken lectures must be replaced with 'chunked' instructional modules—short 10 to 15-minute conceptual inputs interleaved with active learning tasks, peer discussions, and hands-on application exercises. Additionally, teachers must explicitly instruct students in metacognitive focus management, helping them recognize the cognitive costs of media multitasking and cultivate dedicated, distraction-free study habits."
                    },
                    {
                        "heading": "Demand for Personalization and Autonomy in Learning Environments",
                        "explanation": "Having grown up in a digital ecosystem characterized by customized algorithmic feeds (such as personalized media streaming, targeted recommendations, and custom user interfaces), contemporary learners expect high degrees of personalization, choice, and autonomy in their educational experiences. They are increasingly dissatisfied with standardized, one-size-fits-all instructional models that mandate uniform pacing, identical learning tasks, and rigid performance metrics for all students.\n\nModern learners view education as a collaborative, self-directed journey where their individual interests, learning speeds, and personal goals should be recognized and accommodated. They value flexible learning pathways, self-paced online modules, and options to demonstrate mastery through diverse formats—such as producing podcasts, video essays, digital portfolios, or coding projects—rather than relying exclusively on traditional written exams.\n\nFulfilling this demand requires schools to adopt personalized learning frameworks, competency-based progression models, and flexible curricular designs. Empowering learners with choices regarding their learning projects, research topics, and assessment methods fosters deep intrinsic motivation and agency. When education respects learner autonomy and aligns with individual passions, student engagement and academic achievement increase significantly."
                    },
                    {
                        "heading": "Global Consciousness and Social Justice Orientations",
                        "explanation": "Contemporary learners display a profound level of global consciousness, social awareness, and ethical commitment to justice. Through immediate digital exposure to global news, social movements, climate emergencies, and human rights advocacy, today’s youth are acutely aware of worldwide systemic crises. Unlike previous generations, whose worldviews were shaped largely by local or national perspectives, modern learners view themselves as global citizens connected to universal human challenges.\n\nThis global consciousness drives a passion for social justice, environmental sustainability, diversity, and equity. Contemporary learners frequently challenge institutional hypocrisy, discrimination, and ecological neglect, demanding that their schools, communities, and future employers align with high ethical standards. They are drawn to authentic, values-driven learning that addresses real-world issues, demonstrating a strong preference for education that contributes directly to positive social change.\n\nPedagogically, educators can leverage this ethical orientation by incorporating Service Learning, Climate Education, and Global Citizenship projects into the core curriculum. Structuring learning around authentic real-world problems—such as local environmental restoration, community poverty alleviation, or human rights advocacy—engages modern learners' sense of purpose, turning their social consciousness into constructive academic and civic action."
                    },
                    {
                        "heading": "Pedagogical Implications for 21st-Century Educational Systems",
                        "explanation": "The distinct cognitive, socio-emotional, and cultural characteristics of contemporary learners necessitate a fundamental overhaul of traditional educational systems. Continuing to rely on industrial-era schooling models—characterized by standardized testing, passive lecture delivery, isolated subject silos, and authoritarian discipline—creates an unsustainable disconnect between school environments and the lived realities of modern youth.\n\nEducational systems must transition toward 21st-century learning frameworks that emphasize critical thinking, media literacy, creative problem-solving, collaboration, and adaptive digital skills. Teachers must shift from being sole authoritative information providers to learning architects, mentors, and facilitators of inquiry. Classrooms must be re-designed into dynamic, technology-enabled, flexible learning environments that support both collaborative group work and quiet individual reflection.\n\nFurthermore, assessment strategies must evolve to evaluate complex, higher-order competencies rather than rote recall. Utilizing performance-based evaluations, authentic project portfolios, and real-world problem-solving metrics aligns assessment with the actual skills learners require in the modern workforce. By modernizing pedagogical structures to honor the unique strengths and address the specific vulnerabilities of contemporary learners, educational systems can prepare youth to thrive in an increasingly complex global landscape."
                    }
                ],
                "diagram_prompt": "A clean, minimal, 2D vector educational comparison diagram on a solid white background contrasting Previous Generation Learners vs. Contemporary (Gen Z/Alpha) Learners. Two side-by-side comparative rectangular panels: Left Panel (Previous Generations) listing 'Linear Print Processing', 'Information Scarcity', 'Local Community Focus', 'Passive Lecture Recipient'. Right Panel (Contemporary Learners) listing 'Multi-modal Non-Linear Processing', 'Information Ubiquity & AI', 'Global Citizen Consciousness', 'Autonomous Choice & Interactive Learner'. Minimalist style, clear iconography, dark text, soft gray, teal, and navy colors, high clarity, no 3D rendering.",
                "conclusion": "In conclusion, the current generation of learners is fundamentally different from all previous generations due to their upbringing in an all-encompassing, hyper-connected digital ecosystem, coupled with heightened global consciousness and changing cognitive processing patterns. While they possess advanced visual literacy, digital mastery, global awareness, and a passion for social justice, they also navigate challenges related to continuous distraction, socio-emotional stress, and reduced sustained attention spans. Educational institutions must urgently transform traditional instructional practices—embracing multi-modal teaching, personalized learning pathways, social-emotional support, and authentic project-based assessments—to effectively nurture and empower this unique generation of global citizens."
            }
        ]
    }
    
    if (isinstance(agent_raw_output,str)):
        dict_content = json.loads(agent_raw_output)
    else:
        dict_content = agent_raw_output

    if hasattr(dict_content, "model_dump"):
        data = dict_content.model_dump()
    elif hasattr(dict_content, "dict"):
        data = dict_content.dict()
    else:
        data = dict_content

    # dict_content = dict_content.model_dump()
    output_filename = f"Assignment_{chat_data.assignment_no}_{chat_data.student_name}.docx"

    await generate_image_via_advanced_web(data)

    await generate_assignment_docx(
        json_data_str=data,
        output_path=output_filename,
        logo_path="assets/aiou_logo.jpg"
    )
    # questions = data.get("questions", [])
    # print(questions)
    return {
        "status": "success",
        "dict_content": data,
        # "file_name": output_filename,
        "message": "Assignment Word document generated successfully!"
    }

